# Generated by Django 5.1.6 on 2025-03-02 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.TextField(blank=True)),
                ('address_line2', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('emergency_name', models.TextField(blank=True)),
                ('emergency_phone', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('looking_roomate', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
