# Generated by Django 5.1.6 on 2025-03-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
