# Generated by Django 5.1.6 on 2025-03-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/UniVerse/static/img/profile_placeholder.png', max_length=500, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
