# Generated by Django 5.1.6 on 2025-03-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplylisting',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged')], default='New', max_length=20),
        ),
    ]
