# Generated by Django 5.1.6 on 2025-03-06 17:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0003_supplylisting_photo_3_supplylisting_photo_4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rating', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplies.supplylisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
