# Generated by Django 5.1.6 on 2025-02-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingbooking',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Housing.housinglisting'),
            preserve_default=False,
        ),
    ]
