# Generated by Django 5.1.6 on 2025-02-11 06:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0002_housingbooking_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinglisting',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
