# Generated by Django 5.1.6 on 2025-02-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0003_housinglisting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinglisting',
            name='home_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Studio', 'Studio'), ('Loft', 'Loft')], default='Apartment', max_length=20),
        ),
    ]
