# Generated by Django 5.1.6 on 2025-02-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0004_housinglisting_home_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinglisting',
            name='city_state',
            field=models.TextField(blank=True),
        ),
    ]
