# Generated by Django 5.1.6 on 2025-02-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0005_housinglisting_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingbooking',
            name='is_pending',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
