# Generated by Django 5.1.6 on 2025-02-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0006_housingbooking_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinglisting',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=255, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='housinglisting',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=255, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
